linters-settings:
  goimports:
    local-prefixes: github.com/eberlitz/go-nubank
  dupl:
    threshold: 100
  golint:
    min-confidence: 0
  govet:
    check-shadowing: false
  maligned:
    suggest-new: true
  misspell:
    locale: US
  nolintlint:
    allow-leading-space: true # don't require machine-readable nolint directives (i.e. with no leading space)
    allow-unused: false # report any unused nolint directives
    require-explanation: false # don't require an explanation for nolint directives
    require-specific: false # don't require nolint directives to be specific about which linter is being skipped
gocritic:
  enabled-tags:
    - diagnostic
    - experimental
    - opinionated
    - performance
    - style
  disabled-checks:
    - dupImport # https://github.com/go-critic/go-critic/issues/845
    - whyNoLint
    - wrapperFunc
    - ifElseChain
    - octalLiteral

# See explanation of linters at https://golangci-lint.run/usage/linters/
linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - godot
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
    - misspell
    - gocyclo
    - golint
    - unconvert
    - goimports
    - interfacer
    - depguard
    - funlen
    - goprintffuncname
    - gosec
    - whitespace
    - unparam
    - rowserrcheck
    - nolintlint
    - stylecheck
    - nakedret
    - gocritic
    - dupl
    - errorlint
    - goerr113
 
run:
  timeout: 3m
